In [16]:
import numpy as np

R = [[3,1,-1],
      [0,4,2],
      [-2,1,0]]



M = np.array(R)
print(M**100)


[[-2984622845537545263                    1                    1]
 [                   0                    0                    0]
 [                   0                    1                    0]]
